name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"

        #Both commands in one step
      - name: Print Multi-Line shell commands
        run: |
            echo "First Output"
            echo "Second Output"
            
